apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nnxz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nnxz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nnxz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nnxz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nnxz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bfxv-tenant/rhtap-demo-app/hacbs-test-project-nnxz@sha256:5c6979cf7df7ca700da38a882a13ec30fa191f57ee6de360a20515a8bb3b9812
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
